name: enough_mail_flutter
description: Flutter widgets for mail apps. Licensed commercially friendly under MPL 2.0.
version: 0.3.0+1
homepage: https://github.com/enough-software/enough_mail_flutter

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  enough_mail_html: #^0.3.0
    # git:
    #   url: https://github.com/Enough-Software/enough_mail_html.git
    path: ../enough_mail_html
  enough_media: #^0.2.0
    # git:
    #   url: https://github.com/Enough-Software/enough_media.git
    path: ../enough_media
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: